(() => {
"use strict";
const CONFIG=window.APP_CONFIG||{},SUPABASE_READY=Boolean(CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_KEY&&window.supabase),LAT=CONFIG.WEATHER_LATITUDE??-22.47203,LON=CONFIG.WEATHER_LONGITUDE??-43.14837;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WEEKDAYS=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"],PET_DEFAULT_TASKS=["🍽️ Comida","💧 Água","🧹 Caixa de areia","💛 Carinho / brincadeira"];
const THEMES=[
{id:"peach",name:"Pêssego",v:{bg:"#fffaf7",surface:"#fff",s2:"#fff1eb",p:"#df8f7c",pd:"#b86757",sec:"#f3c9bc",a:"#dbe9d5",a2:"#dcd6f0",text:"#433b3a",muted:"#837777",border:"#eaded9",good:"#d7ead0",bad:"#d8e6f4",done:"#eed9a8",unexpected:"#e8d8f2"}},
{id:"lavender",name:"Lavanda",v:{bg:"#fbf9ff",surface:"#fff",s2:"#f1edfb",p:"#9a86c5",pd:"#715d9e",sec:"#d8cff0",a:"#dcebdc",a2:"#f1dbe9",text:"#403b4b",muted:"#7e7789",border:"#e5dff0",good:"#dcebd8",bad:"#dfe6f5",done:"#f0dfb6",unexpected:"#eadcf4"}},
{id:"mint",name:"Menta",v:{bg:"#f8fdfb",surface:"#fff",s2:"#eaf8f1",p:"#78b99a",pd:"#4d8c70",sec:"#c8ead9",a:"#f3dfc4",a2:"#dfe1f5",text:"#34443e",muted:"#74857e",border:"#dcebe4",good:"#d9eddc",bad:"#dceaf4",done:"#f0e0b3",unexpected:"#e7def1"}},
{id:"sky",name:"Céu",v:{bg:"#f8fbff",surface:"#fff",s2:"#eaf3fb",p:"#7caacb",pd:"#527e9e",sec:"#cce1f0",a:"#e1ead1",a2:"#eadcf0",text:"#35434e",muted:"#74818a",border:"#dbe8f0",good:"#dcebd8",bad:"#d7e8f5",done:"#efe0b5",unexpected:"#e9ddf3"}},
{id:"rose",name:"Rosé",v:{bg:"#fff9fb",surface:"#fff",s2:"#fbeaf0",p:"#cf819b",pd:"#9f5b72",sec:"#f0c7d4",a:"#dcebd9",a2:"#e5ddf3",text:"#493a40",muted:"#89747b",border:"#eedde3",good:"#dcebd8",bad:"#dce7f3",done:"#f0ddb2",unexpected:"#eadcf0"}},
{id:"vanilla",name:"Baunilha",v:{bg:"#fffdf7",surface:"#fff",s2:"#fbf2dc",p:"#c49b61",pd:"#92703f",sec:"#eed8ad",a:"#dce9d8",a2:"#e1dded",text:"#463f35",muted:"#827b70",border:"#ebe2d2",good:"#dcebd6",bad:"#dde8f2",done:"#f0dea9",unexpected:"#e9e0ef"}}];
const state={mode:SUPABASE_READY?"online":"demo",supabase:null,session:null,user:null,board:null,boards:[],members:[],plans:[],planChecklist:[],planParticipants:[],tasks:[],taskOccurrences:[],taskExceptions:[],finance:[],bills:[],billPayments:[],shopping:[],pets:[],petLogs:[],petHealth:[],goals:[],stock:[],notices:[],noticeReads:[],availability:[],weather:new Map(),rangeStart:null,rangeEnd:null,page:"today",authMode:"login",activeDate:null,editingPlanId:null,editingTaskId:null,editingShoppingId:null,editingFinanceId:null,editingBillId:null,editingHealthId:null,editingGoalId:null,editingStockId:null,editChecklist:[],editExceptions:[],taskFilter:"all",shoppingFilter:"pending",realtimeChannel:null,billAlertShown:false};

function isoDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return`${y}-${m}-${day}`}
function parseDate(s){const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function addMonths(d,n){const x=new Date(d),day=x.getDate();x.setDate(1);x.setMonth(x.getMonth()+n);x.setDate(Math.min(day,new Date(x.getFullYear(),x.getMonth()+1,0).getDate()));return x}
function today(){return isoDate(new Date())}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function longDate(s){return parseDate(s).toLocaleDateString("pt-BR",{day:"numeric",month:"long",year:"numeric"})}
function weekDay(s){return parseDate(s).toLocaleDateString("pt-BR",{weekday:"long"})}
function memberName(id){return state.members.find(m=>m.user_id===id)?.display_name||"Sem responsável"}
function memberColor(id){return state.members.find(m=>m.user_id===id)?.profile_color||"#df8f7c"}
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2500)}
function setSync(t){$("#syncStatus").textContent=t}
function showOnly(id){["#authScreen","#boardScreen","#app"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDialog(id){const d=$(id);if(d?.open)d.close()}
function applyTheme(id){const t=THEMES.find(x=>x.id===id)||THEMES[0],r=document.documentElement,map={bg:"--bg",surface:"--surface",s2:"--surface-2",p:"--primary",pd:"--primary-dark",sec:"--secondary",a:"--accent",a2:"--accent-2",text:"--text",muted:"--muted",border:"--border",good:"--good",bad:"--bad",done:"--done",unexpected:"--unexpected"};Object.entries(t.v).forEach(([k,v])=>r.style.setProperty(map[k],v));localStorage.setItem("nosso_tempo_theme",t.id)}
function renderThemes(){$("#themeOptions").innerHTML=THEMES.map(t=>`<button class="theme-choice" data-theme="${t.id}"><span class="swatches"><i style="background:${t.v.p}"></i><i style="background:${t.v.s2}"></i><i style="background:${t.v.a2}"></i></span>${t.name}</button>`).join("")}
function defaultRange(){const n=new Date();state.rangeStart=isoDate(n);state.rangeEnd=isoDate(addMonths(n,1));$("#startDate").value=state.rangeStart;$("#endDate").value=state.rangeEnd;updateRangeLabel()}
function updateRangeLabel(){const s=parseDate(state.rangeStart),e=parseDate(state.rangeEnd),sm=s.toLocaleDateString("pt-BR",{month:"short"}).replace(".",""),em=e.toLocaleDateString("pt-BR",{month:"short"}).replace(".","");$("#mobileRangeTitle").textContent=`${s.getDate()} ${sm} — ${e.getDate()} ${em}`}
function inRange(date){return date>=state.rangeStart&&date<=state.rangeEnd}
function getRangeDates(start,end){const a=[];let d=parseDate(start),last=parseDate(end),g=0;while(d<=last&&g<370){a.push(isoDate(d));d=addDays(d,1);g++}return a}
function weatherIcon(c){if(c===0)return"☀️";if([1,2].includes(c))return"🌤️";if(c===3)return"☁️";if([45,48].includes(c))return"🌫️";if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return"🌧️";if([95,96,99].includes(c))return"⛈️";return"🌥️"}
function weatherLabel(c){if(c===0)return"céu limpo";if([1,2].includes(c))return"poucas nuvens";if(c===3)return"nublado";if([45,48].includes(c))return"neblina";if([51,53,55,56,57].includes(c))return"garoa";if([61,63,65,66,67,80,81,82].includes(c))return"chuva";if([95,96,99].includes(c))return"trovoadas";return"tempo variável"}
async function loadWeather(){state.weather.clear();const t=today(),max=isoDate(addDays(new Date(),15)),start=state.rangeStart<t?t:state.rangeStart,end=state.rangeEnd>max?max:state.rangeEnd;if(start<=end)try{const q=new URLSearchParams({latitude:LAT,longitude:LON,daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max",timezone:"America/Sao_Paulo",start_date:start,end_date:end}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`),d=await r.json();(d.daily?.time||[]).forEach((date,i)=>state.weather.set(date,{code:d.daily.weather_code[i],max:Math.round(d.daily.temperature_2m_max[i]),min:Math.round(d.daily.temperature_2m_min[i]),precip:d.daily.precipitation_probability_max[i]??0}))}catch(e){console.warn(e)}updateWeatherUI();renderCalendar();renderToday()}
function updateWeatherUI(){const w=state.weather.get(today());if(!w)return;$("#todayWeatherIcon").textContent=weatherIcon(w.code);$("#todayWeatherTitle").textContent=`${w.max}° / ${w.min}° • ${weatherLabel(w.code)}`;$("#todayWeatherText").textContent=`${w.precip}% de chance de chuva.`;$("#todayPageWeatherIcon").textContent=weatherIcon(w.code);$("#todayPageWeatherTitle").textContent=`${w.max}° / ${w.min}° • ${weatherLabel(w.code)}`;$("#todayPageWeatherText").textContent=`${w.precip}% de chuva • Cascatinha`}
function effectivePlanStatus(p){if(p.status==="done")return"done";if(p.status==="unexpected")return"unexpected";if(p.status==="skipped")return"missed";if(p.plan_date<today())return"missed";return"planned"}
function statusText(s){return({done:"Realizado",unexpected:"Imprevisto",missed:"Não realizado",planned:"Planejado"})[s]||s}
function effectiveTaskStatus(t){if(t.is_done)return"done";if(t.unforeseen)return"unexpected";if(t.due_date&&t.due_date<today())return"missed";return"planned"}

function demoLoad(){const d=JSON.parse(localStorage.getItem("nosso_tempo_v5_demo")||"{}");Object.assign(state,{user:{id:"demo-user",email:"demo@local"},session:{},board:{id:"demo-board",name:"Nosso Tempo",join_code:"LOCAL"},boards:[{id:"demo-board",name:"Nosso Tempo",join_code:"LOCAL"}],members:d.members||[{user_id:"demo-user",display_name:"Você",profile_color:"#df8f7c",profile_note:""},{user_id:"demo-partner",display_name:"Outra pessoa",profile_color:"#8eabc9",profile_note:""}],plans:d.plans||[],planChecklist:d.planChecklist||[],planParticipants:d.planParticipants||[],tasks:d.tasks||[],taskOccurrences:d.taskOccurrences||[],taskExceptions:d.taskExceptions||[],finance:d.finance||[],bills:d.bills||[],billPayments:d.billPayments||[],shopping:d.shopping||[],pets:d.pets||[{id:"simba",name:"Simba",species:"gato",coat:"rajado",emoji:"🐯",sort_order:1},{id:"nala",name:"Nala",species:"gato",coat:"preto",emoji:"🐈‍⬛",sort_order:2},{id:"gris",name:"Gris",species:"gato",coat:"cinza",emoji:"🩶",sort_order:3},{id:"xayah",name:"Xayah",species:"gata",coat:"rajada",emoji:"🐯",sort_order:4}],petLogs:d.petLogs||[],petHealth:d.petHealth||[],goals:d.goals||[],stock:d.stock||[],notices:d.notices||[],noticeReads:d.noticeReads||[],availability:d.availability||[]})}
function demoSave(){localStorage.setItem("nosso_tempo_v5_demo",JSON.stringify({members:state.members,plans:state.plans,planChecklist:state.planChecklist,planParticipants:state.planParticipants,tasks:state.tasks,taskOccurrences:state.taskOccurrences,taskExceptions:state.taskExceptions,finance:state.finance,bills:state.bills,billPayments:state.billPayments,shopping:state.shopping,pets:state.pets,petLogs:state.petLogs,petHealth:state.petHealth,goals:state.goals,stock:state.stock,notices:state.notices,noticeReads:state.noticeReads,availability:state.availability}))}
async function safe(name,p){const{data,error}=await p;if(error){console.error(name,error);if(/does not exist|column .* does not exist/i.test(error.message||""))toast("Rode a MIGRACAO_V5.sql no Supabase.");return[]}return data||[]}
async function initOnline(){state.supabase=window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const{data}=await state.supabase.auth.getSession();state.session=data.session;state.user=data.session?.user||null;state.supabase.auth.onAuthStateChange((_e,s)=>{state.session=s;state.user=s?.user||null});if(!state.user)return showOnly("#authScreen");await loadBoards()}
async function loadBoards(){const m=await safe("memberships",state.supabase.from("board_members").select("board_id,display_name").eq("user_id",state.user.id));if(!m.length){state.boards=[];renderExistingBoards();return showOnly("#boardScreen")}state.boards=await safe("boards",state.supabase.from("boards").select("id,name,join_code,created_at").in("id",m.map(x=>x.board_id)));const last=localStorage.getItem("nosso_tempo_board_id"),b=state.boards.find(x=>x.id===last)||state.boards[0];if(b)await selectBoard(b)}
async function selectBoard(b){state.board=b;localStorage.setItem("nosso_tempo_board_id",b.id);await state.supabase.rpc("ensure_default_pets",{p_board_id:b.id});await refreshAll(true);subscribeRealtime();enterApp()}
async function refreshAll(first=false){if(state.mode==="demo"){demoLoad();renderAll();return}if(!state.board)return;setSync("sincronizando...");const id=state.board.id;const r=await Promise.all([
safe("members",state.supabase.from("board_members").select("user_id,display_name,profile_color,profile_note,joined_at").eq("board_id",id).order("joined_at")),
safe("plans",state.supabase.from("day_plans").select("*").eq("board_id",id).order("plan_date").order("start_time")),
safe("planChecklist",state.supabase.from("plan_checklist_items").select("*").eq("board_id",id).order("position")),
safe("planParticipants",state.supabase.from("plan_participants").select("*").eq("board_id",id)),
safe("tasks",state.supabase.from("shared_tasks").select("*").eq("board_id",id).order("created_at",{ascending:false})),
safe("taskOccurrences",state.supabase.from("shared_task_occurrences").select("*").eq("board_id",id)),
safe("taskExceptions",state.supabase.from("shared_task_exceptions").select("*").eq("board_id",id)),
safe("finance",state.supabase.from("finance_entries").select("*").eq("board_id",id).order("entry_date",{ascending:false})),
safe("bills",state.supabase.from("recurring_bills").select("*").eq("board_id",id).order("due_day")),
safe("billPayments",state.supabase.from("recurring_bill_payments").select("*").eq("board_id",id)),
safe("shopping",state.supabase.from("shopping_items").select("*").eq("board_id",id).order("created_at",{ascending:false})),
safe("pets",state.supabase.from("pets").select("*").eq("board_id",id).order("sort_order")),
safe("petLogs",state.supabase.from("pet_care_logs").select("*").eq("board_id",id).order("care_date",{ascending:false})),
safe("petHealth",state.supabase.from("pet_health_records").select("*").eq("board_id",id).order("record_date",{ascending:false})),
safe("goals",state.supabase.from("goals").select("*").eq("board_id",id).order("created_at")),
safe("stock",state.supabase.from("inventory_items").select("*").eq("board_id",id).order("item_name")),
safe("notices",state.supabase.from("notices").select("*").eq("board_id",id).order("created_at",{ascending:false})),
safe("noticeReads",state.supabase.from("notice_reads").select("*").eq("board_id",id)),
safe("availability",state.supabase.from("availability_blocks").select("*").eq("board_id",id).order("start_time"))
]);[state.members,state.plans,state.planChecklist,state.planParticipants,state.tasks,state.taskOccurrences,state.taskExceptions,state.finance,state.bills,state.billPayments,state.shopping,state.pets,state.petLogs,state.petHealth,state.goals,state.stock,state.notices,state.noticeReads,state.availability]=r;setSync("sincronizado agora");renderAll();if(first)setTimeout(showUnreadNotices,250)}
function subscribeRealtime(){if(state.mode!=="online"||!state.board)return;if(state.realtimeChannel)state.supabase.removeChannel(state.realtimeChannel);const tables=["day_plans","shared_tasks","shared_task_occurrences","shared_task_exceptions","finance_entries","recurring_bills","recurring_bill_payments","shopping_items","pet_care_logs","pet_health_records","goals","inventory_items","notices","notice_reads","availability_blocks","plan_checklist_items","plan_participants","board_members"],ch=state.supabase.channel(`v5-${state.board.id}`);tables.forEach(table=>ch.on("postgres_changes",{event:"*",schema:"public",table,filter:`board_id=eq.${state.board.id}`},async p=>{const newNotice=table==="notices"&&p.eventType==="INSERT"&&p.new?.created_by!==state.user.id;await refreshAll(false);if(newNotice){toast(`💌 Novo recado: ${p.new.title}`);if("Notification"in window&&Notification.permission==="granted")new Notification("Nosso Tempo 💌",{body:p.new.title});showUnreadNotices()}}));state.realtimeChannel=ch.subscribe()}
function enterApp(){$("#appTitle").textContent=state.board?.name||"Nosso Tempo";$("#inviteCode").textContent=state.board?.join_code||"LOCAL";showOnly("#app");setPage("today");renderAll();setTimeout(notifyDueBillsOnEntry,500);loadWeather();if(state.mode==="demo")$("#demoBanner").classList.remove("hidden")}
function renderExistingBoards(){$("#existingBoards").innerHTML=state.boards.length?`<p class="eyebrow">SUAS AGENDAS</p>`+state.boards.map(b=>`<button class="existing-board" data-board-id="${b.id}"><span><strong>${esc(b.name)}</strong><br><small class="muted">código ${esc(b.join_code)}</small></span><span>→</span></button>`).join(""):""}
function renderMemberSelects(){const o=state.members.map(m=>`<option value="${m.user_id}">${esc(m.display_name)}</option>`).join("");["#chooserSelect","#taskAssignedTo","#shoppingAssignedTo","#billResponsible"].forEach(sel=>$(sel).innerHTML=`<option value="">Sem responsável</option>${o}`);$("#healthPet").innerHTML=state.pets.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}

function plansOn(date){return state.plans.filter(p=>p.plan_date===date).sort((a,b)=>(a.start_time||"99:99").localeCompare(b.start_time||"99:99"))}
function renderCalendar(){if(!state.rangeStart)return;updateRangeLabel();const dates=getRangeDates(state.rangeStart,state.rangeEnd),first=parseDate(state.rangeStart),blanks=(first.getDay()+6)%7;let html=Array.from({length:blanks},()=>`<div class="blank-day"></div>`).join("");for(const date of dates){const d=parseDate(date),w=state.weather.get(date),plans=plansOn(date),show=plans.slice(0,4);html+=`<article class="day-card ${date===today()?"today":""}" data-date="${date}"><div class="day-head"><span class="day-number"><strong>${d.getDate()}</strong><small>${d.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","")}</small></span>${w?`<span class="weather-mini">${weatherIcon(w.code)} <span>${w.max}° • ${w.precip}%</span></span>`:`<span class="weather-mini">🗓️ <span>—</span></span>`}</div><div class="day-events">${show.map(p=>{const s=effectivePlanStatus(p),opt=p.selected_option==="bad"?p.bad_option:p.selected_option==="good"?p.good_option:(p.good_option||p.bad_option||"");return`<button class="event-chip ${s}" data-plan-id="${p.id}" style="border-left-color:${memberColor(p.chooser_user_id)}"><span class="event-topline">${p.start_time?String(p.start_time).slice(0,5):"sem hora"}${p.end_time?`–${String(p.end_time).slice(0,5)}`:""} • ${esc(memberName(p.chooser_user_id))}</span><span class="event-title">${s==="done"?"✓ ":s==="unexpected"?"⚡ ":s==="missed"?"○ ":""}${esc(p.title||"Atividade")}</span>${opt?`<span class="event-option">${esc(opt)}</span>`:""}</button>`}).join("")}${plans.length>4?`<span class="more-events">+${plans.length-4}</span>`:""}</div></article>`}$("#calendarGrid").innerHTML=html;const r=state.plans.filter(p=>inRange(p.plan_date)),done=r.filter(p=>effectivePlanStatus(p)==="done").length,miss=r.filter(p=>effectivePlanStatus(p)==="missed").length;$("#calendarQuickStat").textContent=`${done} realizados`;$("#calendarQuickSub").textContent=miss?`${miss} não realizado(s).`:"Tudo em dia."}
function openDay(date){state.activeDate=date;$("#dayDialogWeekday").textContent=weekDay(date).toUpperCase();$("#dayDialogDate").textContent=longDate(date);const w=state.weather.get(date);$("#dayDialogWeather").innerHTML=w?`${weatherIcon(w.code)} <strong>${w.max}° / ${w.min}°</strong> • ${w.precip}% chuva`:`🗓️ Previsão ainda indisponível.`;const p=plansOn(date);$("#dayPlanList").innerHTML=p.length?p.map(x=>{const s=effectivePlanStatus(x);return`<article class="day-plan-card"><button class="circle-check ${s==="done"?"checked":s==="unexpected"?"unexpected":""}" data-quick-plan="${x.id}">${s==="done"?"✓":s==="unexpected"?"⚡":""}</button><div class="plan-copy"><div class="plan-title">${esc(x.title)}</div><div class="plan-meta">${x.start_time?String(x.start_time).slice(0,5):"sem hora"}${x.end_time?`–${String(x.end_time).slice(0,5)}`:""} • ${statusText(s)}</div></div><button class="icon-mini" data-edit-plan="${x.id}">✎</button></article>`}).join(""):`<div class="empty-state">Nenhuma atividade ainda.</div>`;openDialog("#dayDialog")}
function participantIds(id){const r=state.planParticipants.filter(x=>x.plan_id===id);return r.length?r.map(x=>x.user_id):state.members.map(m=>m.user_id)}
function selectedParticipants(){return $$("[data-participant]:checked").map(x=>x.dataset.participant)}
function intervalsOverlap(a1,a2,b1,b2){if(!a1||!b1)return false;a2=a2||a1;b2=b2||b1;return a1<b2&&b1<a2}
function availabilityFor(uid,date,start,end,ignorePlan=null){if(!start)return[{type:"unknown",text:"escolha um horário"}];const wd=parseDate(date).getDay(),blocks=state.availability.filter(b=>b.user_id===uid&&(b.specific_date===date||(!b.specific_date&&Number(b.weekday)===wd))),messages=[];for(const b of blocks){if(b.availability_type==="busy"&&intervalsOverlap(start,end||start,String(b.start_time).slice(0,5),String(b.end_time).slice(0,5)))messages.push({type:"busy",text:`ocupado — ${b.label} (${String(b.start_time).slice(0,5)}–${String(b.end_time).slice(0,5)})`})}const explicitAvailable=blocks.filter(b=>b.availability_type==="available");if(explicitAvailable.length&&!explicitAvailable.some(b=>intervalsOverlap(start,end||start,String(b.start_time).slice(0,5),String(b.end_time).slice(0,5))))messages.push({type:"busy",text:"fora do período marcado como disponível"});for(const p of plansOn(date)){if(p.id===ignorePlan)continue;if(!participantIds(p.id).includes(uid))continue;if(intervalsOverlap(start,end||start,String(p.start_time||"").slice(0,5),String(p.end_time||p.start_time||"").slice(0,5)))messages.push({type:"busy",text:`conflito com "${p.title}" (${String(p.start_time||"").slice(0,5)}–${String(p.end_time||p.start_time||"").slice(0,5)})`})}return messages.length?messages:[{type:blocks.length?"available":"unknown",text:blocks.length?"sem conflito":"sem disponibilidade cadastrada"}]}
function updateAvailabilityWarning(){const start=$("#planTime").value,end=$("#planEndTime").value,ids=selectedParticipants();$("#availabilityWarning").innerHTML=ids.flatMap(id=>availabilityFor(id,state.activeDate,start,end,state.editingPlanId).map(a=>`<div class="availability-status ${a.type}"><strong>${esc(memberName(id))}:</strong> ${esc(a.text)}</div>`)).join("")}
function openPlan(id=null,date=state.activeDate||today()){const p=id?state.plans.find(x=>x.id===id):null;state.editingPlanId=id;state.activeDate=p?.plan_date||date;$("#dialogWeekday").textContent=weekDay(state.activeDate).toUpperCase();$("#dialogDate").textContent=longDate(state.activeDate);const w=state.weather.get(state.activeDate);$("#dialogWeather").innerHTML=w?`${weatherIcon(w.code)} ${w.max}° / ${w.min}° • ${w.precip}% chuva`:"🗓️ Sem previsão.";$("#planTitle").value=p?.title||"";$("#chooserSelect").value=p?.chooser_user_id||"";$("#category").value=p?.category||"💛 Tempo juntos";$("#planTime").value=p?.start_time?String(p.start_time).slice(0,5):"";$("#planEndTime").value=p?.end_time?String(p.end_time).slice(0,5):"";$("#goodOption").value=p?.good_option||"";$("#badOption").value=p?.bad_option||"";$("#selectedOption").value=p?.selected_option||"auto";$("#notes").value=p?.notes||"";$("#incidentReason").value=p?.incident_reason||"";$("#activityDone").checked=p?.status==="done";$("#activityUnexpected").checked=p?.status==="unexpected";$("#incidentReasonWrap").classList.toggle("hidden",!$("#activityUnexpected").checked);let rem="";if(p?.reminder_at){const d=new Date(p.reminder_at),l=new Date(d.getTime()-d.getTimezoneOffset()*60000);rem=l.toISOString().slice(0,16)}$("#reminderAt").value=rem;const selected=new Set(p?participantIds(p.id):state.members.map(m=>m.user_id));$("#participantChecks").innerHTML=state.members.map(m=>`<label class="participant-pill"><input type="checkbox" data-participant="${m.user_id}" ${selected.has(m.user_id)?"checked":""}/><span class="member-color" style="background:${m.profile_color||"#df8f7c"}"></span>${esc(m.display_name)}</label>`).join("");state.editChecklist=p?state.planChecklist.filter(x=>x.plan_id===p.id).map(x=>({...x})):[];renderPlanChecklist();$("#deletePlan").style.visibility=p?"visible":"hidden";closeDialog("#dayDialog");openDialog("#planDialog");updateAvailabilityWarning()}
function renderPlanChecklist(){$("#planChecklistList").innerHTML=state.editChecklist.length?state.editChecklist.map((x,i)=>`<div class="mini-check-item"><input type="checkbox" data-plan-check="${i}" ${x.is_done?"checked":""}/><span>${esc(x.item_text)}</span><button type="button" data-remove-plan-check="${i}">×</button></div>`).join(""):`<p class="muted tiny">Sem subtarefas.</p>`}
async function savePlan(e){e.preventDefault();const start=$("#planTime").value,end=$("#planEndTime").value;if(start&&end&&end<=start)return toast("O horário final precisa ser depois do início.");const payload={board_id:state.board.id,plan_date:state.activeDate,title:$("#planTitle").value.trim(),chooser_user_id:$("#chooserSelect").value||null,category:$("#category").value,good_option:$("#goodOption").value.trim()||null,bad_option:$("#badOption").value.trim()||null,start_time:start||null,end_time:end||null,selected_option:$("#selectedOption").value,status:$("#activityUnexpected").checked?"unexpected":$("#activityDone").checked?"done":"planned",reminder_at:$("#reminderAt").value?new Date($("#reminderAt").value).toISOString():null,notes:$("#notes").value.trim()||null,incident_reason:$("#incidentReason").value.trim()||null,updated_by:state.user.id,updated_at:new Date().toISOString()};if(!payload.title)return toast("Dê um nome para a atividade.");let id=state.editingPlanId;if(state.mode==="demo"){if(id)Object.assign(state.plans.find(x=>x.id===id),payload);else{id=crypto.randomUUID();state.plans.push({...payload,id,created_by:state.user.id,created_at:new Date().toISOString()})}state.planParticipants=state.planParticipants.filter(x=>x.plan_id!==id);selectedParticipants().forEach(uid=>state.planParticipants.push({plan_id:id,user_id:uid}));state.planChecklist=state.planChecklist.filter(x=>x.plan_id!==id);state.editChecklist.forEach((x,i)=>state.planChecklist.push({id:crypto.randomUUID(),plan_id:id,item_text:x.item_text,is_done:x.is_done,position:i}));demoSave()}else{const r=id?await state.supabase.from("day_plans").update(payload).eq("id",id).select().single():await state.supabase.from("day_plans").insert({...payload,created_by:state.user.id}).select().single();if(r.error)return toast(r.error.message);id=r.data.id;await state.supabase.from("plan_participants").delete().eq("plan_id",id);const parts=selectedParticipants();if(parts.length)await state.supabase.from("plan_participants").insert(parts.map(uid=>({board_id:state.board.id,plan_id:id,user_id:uid})));await state.supabase.from("plan_checklist_items").delete().eq("plan_id",id);if(state.editChecklist.length)await state.supabase.from("plan_checklist_items").insert(state.editChecklist.map((x,i)=>({board_id:state.board.id,plan_id:id,item_text:x.item_text,is_done:x.is_done,position:i})));await refreshAll(false)}closeDialog("#planDialog");renderAll();toast("Atividade salva ♡")}
async function deletePlan(){const id=state.editingPlanId;if(!id)return;if(state.mode==="demo"){state.plans=state.plans.filter(x=>x.id!==id);state.planChecklist=state.planChecklist.filter(x=>x.plan_id!==id);state.planParticipants=state.planParticipants.filter(x=>x.plan_id!==id);demoSave()}else{await state.supabase.from("day_plans").delete().eq("id",id);await refreshAll(false)}closeDialog("#planDialog");renderAll()}
async function quickPlan(id){const p=state.plans.find(x=>x.id===id),next=p.status==="done"?"planned":"done";if(state.mode==="demo"){p.status=next;demoSave();renderAll();if($("#dayDialog").open)openDay(p.plan_date)}else{await state.supabase.from("day_plans").update({status:next,updated_at:new Date().toISOString()}).eq("id",id);await refreshAll(false);if($("#dayDialog").open)openDay(p.plan_date)}}

function isRecurringTask(t){return(t.recurrence_type||"none")!=="none"}
function recurrenceStart(t){return t.recurrence_start||t.due_date||String(t.created_at||today()).slice(0,10)}
function taskException(t,date){return state.taskExceptions.find(x=>x.task_id===t.id&&x.exception_date===date)}
function taskOccursOn(t,date){if(taskException(t,date))return false;if(!isRecurringTask(t))return t.due_date===date;const start=recurrenceStart(t);if(date<start||t.recurrence_end&&date>t.recurrence_end)return false;const d=parseDate(date),s=parseDate(start),wd=d.getDay(),type=t.recurrence_type;if(type==="daily")return true;if(type==="weekdays")return wd>=1&&wd<=5;if(type==="weekly")return wd===s.getDay();if(type==="custom_weekdays")return(t.recurrence_weekdays||[]).map(Number).includes(wd);if(type==="monthly")return d.getDate()===s.getDate();return false}
function taskOccurrence(t,date){return state.taskOccurrences.find(x=>x.task_id===t.id&&x.occurrence_date===date)}
function occurrenceStatus(t,date){if(!isRecurringTask(t))return effectiveTaskStatus(t);const o=taskOccurrence(t,date);if(o?.is_done)return"done";if(o?.unforeseen)return"unexpected";if(date<today())return"missed";return"planned"}
function recurrenceText(t){const d=parseDate(recurrenceStart(t)),type=t.recurrence_type;if(type==="daily")return"Todos os dias";if(type==="weekdays")return"Segunda a sexta";if(type==="weekly")return`Toda ${WEEKDAYS[d.getDay()].toLowerCase()}`;if(type==="custom_weekdays")return`Toda semana: ${(t.recurrence_weekdays||[]).map(Number).map(x=>WEEKDAYS[x].slice(0,3)).join(", ")}`;if(type==="monthly")return`Todo dia ${d.getDate()}`;return"Não repete"}
function recurrenceDates(t,from,to){const a=[];let d=parseDate(from),last=parseDate(to),g=0;while(d<=last&&g<400){const s=isoDate(d);if(taskOccursOn(t,s))a.push(s);d=addDays(d,1);g++}return a}
function nextOccurrence(t,from=today()){if(!isRecurringTask(t))return t.due_date;let d=parseDate(from);for(let i=0;i<370;i++){const s=isoDate(d);if(taskOccursOn(t,s))return s;d=addDays(d,1)}return null}
function taskInstances(from,to){const rows=[];for(const t of state.tasks){if(isRecurringTask(t)){for(const d of recurrenceDates(t,from,to))rows.push({task:t,date:d,status:occurrenceStatus(t,d)})}else{const d=t.due_date||String(t.created_at||today()).slice(0,10);if(d>=from&&d<=to)rows.push({task:t,date:d,status:effectiveTaskStatus(t)})}}return rows}
function selectedRecurDays(){return $$("[data-recur-day]:checked").map(x=>Number(x.dataset.recurDay))}
function updateRecurrenceUI(){const type=$("#taskRecurrence").value,rec=type!=="none";$("#recurrenceEndWrap").classList.toggle("hidden",!rec);$("#customWeekdaysWrap").classList.toggle("hidden",type!=="custom_weekdays");$("#routineExceptionsWrap").classList.toggle("hidden",!rec);$("#singleTaskStatus").classList.toggle("hidden",rec);$("#recurringStatusHint").classList.toggle("hidden",!rec);const d=parseDate($("#taskDueDate").value||today()),days=selectedRecurDays().map(x=>WEEKDAYS[x].slice(0,3));let text="";if(type==="daily")text="Todos os dias.";else if(type==="weekdays")text="De segunda a sexta.";else if(type==="weekly")text=`Toda ${WEEKDAYS[d.getDay()].toLowerCase()}.`;else if(type==="custom_weekdays")text=days.length?days.join(", "):"Escolha os dias.";else if(type==="monthly")text=`Todo dia ${d.getDate()} do mês.`;$("#recurrencePreview").textContent=text;$("#recurrencePreview").classList.toggle("hidden",!rec)}
function renderExceptions(){$("#taskExceptionList").innerHTML=state.editExceptions.map((x,i)=>`<span class="exception-chip">🚫 ${new Date(x.exception_date+"T12:00").toLocaleDateString("pt-BR")}${x.reason?` • ${esc(x.reason)}`:""}<button type="button" data-remove-exception="${i}">×</button></span>`).join("")}
function renderTasks(){const from=isoDate(addDays(new Date(),-30)),to=isoDate(addDays(new Date(),30)),inst=taskInstances(from,to),c={done:0,missed:0,unexpected:0,planned:0};inst.filter(x=>x.date<=today()).forEach(x=>c[x.status]++);$("#taskSummaryCards").innerHTML=[["✅","Realizadas • 30 dias",c.done,"goodish"],["○","Não realizadas",c.missed,"badish"],["⚡","Imprevistos",c.unexpected,"warnish"],["🔁","Rotinas",state.tasks.filter(isRecurringTask).length,""]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");let rows=[];if(state.taskFilter==="today")rows=taskInstances(today(),today());else if(["done","missed","unexpected"].includes(state.taskFilter))rows=inst.filter(x=>x.status===state.taskFilter);else{const t=state.tasks.filter(x=>state.taskFilter!=="recurring"||isRecurringTask(x));rows=t.map(task=>({task,date:isRecurringTask(task)?nextOccurrence(task):(task.due_date||today()),status:isRecurringTask(task)?occurrenceStatus(task,nextOccurrence(task)||today()):effectiveTaskStatus(task),template:true}))}$("#taskList").innerHTML=rows.length?rows.map(r=>{const t=r.task,rec=isRecurringTask(t),s=r.status,can=!r.template||r.date===today();return`<article class="list-card">${can?`<button class="circle-check ${s==="done"?"checked":s==="unexpected"?"unexpected":""}" data-task-toggle="${t.id}" data-occurrence-date="${r.date}">${s==="done"?"✓":s==="unexpected"?"⚡":""}</button>`:`<span class="circle-check">${rec?"↻":""}</span>`}<div class="list-card-main"><div class="list-card-title">${esc(t.title)}</div><div class="list-card-meta"><span>${esc(t.category)}</span><span>📅 ${r.date?new Date(r.date+"T12:00").toLocaleDateString("pt-BR"):"—"}</span>${t.assigned_to?`<span>👤 ${esc(memberName(t.assigned_to))}</span>`:""}<span class="priority-badge ${t.priority||"normal"}">${t.priority==="urgent"?"Urgente":t.priority==="important"?"Importante":"Normal"}</span>${rec?`<span class="repeat-badge">🔁 ${esc(recurrenceText(t))}</span>`:`<span class="status-label ${s}">${statusText(s)}</span>`}</div>${rec&&state.taskExceptions.some(x=>x.task_id===t.id)?`<div class="tiny muted">📆 ${state.taskExceptions.filter(x=>x.task_id===t.id).length} data(s) pulada(s)</div>`:""}</div><div class="list-actions">${can?`<button class="icon-mini" data-task-unexpected="${t.id}" data-occurrence-date="${r.date}">⚡</button>`:""}<button class="icon-mini" data-edit-task="${t.id}">✎</button></div></article>`}).join(""):`<div class="empty-state">Nenhuma tarefa aqui.</div>`}
function openTask(id=null){state.editingTaskId=id;const t=id?state.tasks.find(x=>x.id===id):null;$("#taskDialogTitle").textContent=t?"Editar tarefa":"Nova tarefa";$("#taskTitle").value=t?.title||"";$("#taskCategory").value=t?.category||"🏠 Casa";$("#taskPriority").value=t?.priority||"normal";$("#taskRecurrence").value=t?.recurrence_type||"none";$("#taskDueDate").value=t?(isRecurringTask(t)?recurrenceStart(t):(t.due_date||today())):today();$("#taskRecurrenceEnd").value=t?.recurrence_end||"";$$("[data-recur-day]").forEach(x=>x.checked=(t?.recurrence_weekdays||[]).map(Number).includes(Number(x.dataset.recurDay)));$("#taskAssignedTo").value=t?.assigned_to||"";$("#taskNotes").value=t?.notes||"";$("#taskDone").checked=!!t?.is_done;$("#taskUnexpected").checked=!!t?.unforeseen;state.editExceptions=t?state.taskExceptions.filter(x=>x.task_id===t.id).map(x=>({...x})):[];renderExceptions();updateRecurrenceUI();$("#deleteTask").style.visibility=t?"visible":"hidden";openDialog("#taskDialog")}
async function saveTask(e){e.preventDefault();const rec=$("#taskRecurrence").value,start=$("#taskDueDate").value||today(),days=selectedRecurDays();if(rec==="custom_weekdays"&&!days.length)return toast("Escolha pelo menos um dia.");const recurring=rec!=="none",payload={board_id:state.board.id,title:$("#taskTitle").value.trim(),category:$("#taskCategory").value,priority:$("#taskPriority").value,due_date:recurring?null:start,recurrence_type:rec,recurrence_start:recurring?start:null,recurrence_end:recurring?($("#taskRecurrenceEnd").value||null):null,recurrence_weekdays:rec==="custom_weekdays"?days:null,assigned_to:$("#taskAssignedTo").value||null,is_done:recurring?false:$("#taskDone").checked,unforeseen:recurring?false:$("#taskUnexpected").checked,notes:$("#taskNotes").value.trim()||null,updated_at:new Date().toISOString()};let id=state.editingTaskId;if(state.mode==="demo"){if(id)Object.assign(state.tasks.find(x=>x.id===id),payload);else{id=crypto.randomUUID();state.tasks.push({...payload,id,created_by:state.user.id,created_at:new Date().toISOString()})}state.taskExceptions=state.taskExceptions.filter(x=>x.task_id!==id);state.editExceptions.forEach(x=>state.taskExceptions.push({...x,id:crypto.randomUUID(),task_id:id,board_id:state.board.id}));demoSave()}else{const r=id?await state.supabase.from("shared_tasks").update(payload).eq("id",id).select().single():await state.supabase.from("shared_tasks").insert({...payload,created_by:state.user.id}).select().single();if(r.error)return toast(r.error.message);id=r.data.id;await state.supabase.from("shared_task_exceptions").delete().eq("task_id",id);if(state.editExceptions.length)await state.supabase.from("shared_task_exceptions").insert(state.editExceptions.map(x=>({board_id:state.board.id,task_id:id,exception_date:x.exception_date,reason:x.reason||null,created_by:state.user.id})));await refreshAll(false)}closeDialog("#taskDialog");renderAll();toast("Tarefa salva.")}
async function toggleTask(id,mode,date){const t=state.tasks.find(x=>x.id===id);if(isRecurringTask(t)){const cur=taskOccurrence(t,date),payload={board_id:state.board.id,task_id:id,occurrence_date:date,is_done:mode==="done"?!cur?.is_done:false,unforeseen:mode==="unexpected"?!cur?.unforeseen:false,completed_by:mode==="done"?state.user.id:null,completed_at:mode==="done"?new Date().toISOString():null,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(cur)Object.assign(cur,payload);else state.taskOccurrences.push({...payload,id:crypto.randomUUID()});demoSave()}else{await state.supabase.from("shared_task_occurrences").upsert(payload,{onConflict:"task_id,occurrence_date"});await refreshAll(false)}}else{const patch=mode==="unexpected"?{unforeseen:!t.unforeseen,is_done:false}:{is_done:!t.is_done,unforeseen:false};if(state.mode==="demo"){Object.assign(t,patch);demoSave()}else{await state.supabase.from("shared_tasks").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);await refreshAll(false)}}renderAll()}
async function deleteTask(){const id=state.editingTaskId;if(!id)return;if(state.mode==="demo"){state.tasks=state.tasks.filter(x=>x.id!==id);state.taskOccurrences=state.taskOccurrences.filter(x=>x.task_id!==id);state.taskExceptions=state.taskExceptions.filter(x=>x.task_id!==id);demoSave()}else{await state.supabase.from("shared_tasks").delete().eq("id",id);await refreshAll(false)}closeDialog("#taskDialog");renderAll()}

function renderShopping(){const pending=state.shopping.filter(x=>!x.is_bought),bought=state.shopping.filter(x=>x.is_bought),est=pending.reduce((a,x)=>a+Number(x.estimated_price||0),0);$("#shoppingMetrics").innerHTML=[["🛒","Pendentes",pending.length,""],["✅","Comprados",bought.length,"goodish"],["💵","Estimativa",money(est),"money"],["👥","Com responsável",pending.filter(x=>x.assigned_to).length,""]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");let list=state.shopping;if(state.shoppingFilter==="pending")list=list.filter(x=>!x.is_bought);if(state.shoppingFilter==="bought")list=list.filter(x=>x.is_bought);$("#shoppingList").innerHTML=list.length?list.map(x=>`<article class="list-card"><button class="circle-check ${x.is_bought?"checked":""}" data-shopping-toggle="${x.id}">${x.is_bought?"✓":""}</button><div class="list-card-main"><div class="list-card-title">${esc(x.item_name)} ${x.quantity?`• ${esc(x.quantity)}`:""}</div><div class="list-card-meta"><span>${esc(x.category)}</span>${x.assigned_to?`<span>👤 ${esc(memberName(x.assigned_to))}</span>`:""}${x.estimated_price!=null?`<span>≈ ${money(x.estimated_price)}</span>`:""}${x.finance_entry_id?`<span>💰 lançado no Banquinho</span>`:""}</div></div><button class="icon-mini" data-edit-shopping="${x.id}">✎</button></article>`).join(""):`<div class="empty-state">Lista vazia.</div>`}
function openShopping(id=null){state.editingShoppingId=id;const x=id?state.shopping.find(y=>y.id===id):null;$("#shoppingDialogTitle").textContent=x?"Editar item":"Novo item";$("#shoppingName").value=x?.item_name||"";$("#shoppingQty").value=x?.quantity||"";$("#shoppingCategory").value=x?.category||"🛒 Mercado";$("#shoppingAssignedTo").value=x?.assigned_to||"";$("#shoppingEstimated").value=x?.estimated_price??"";$("#shoppingNotes").value=x?.notes||"";$("#deleteShopping").style.visibility=x?"visible":"hidden";openDialog("#shoppingDialog")}
async function saveShopping(e){e.preventDefault();const p={board_id:state.board.id,item_name:$("#shoppingName").value.trim(),quantity:$("#shoppingQty").value.trim()||null,category:$("#shoppingCategory").value,assigned_to:$("#shoppingAssignedTo").value||null,estimated_price:$("#shoppingEstimated").value?Number($("#shoppingEstimated").value):null,notes:$("#shoppingNotes").value.trim()||null,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingShoppingId)Object.assign(state.shopping.find(x=>x.id===state.editingShoppingId),p);else state.shopping.unshift({...p,id:crypto.randomUUID(),is_bought:false,created_by:state.user.id,created_at:new Date().toISOString()});demoSave()}else{const q=state.editingShoppingId?state.supabase.from("shopping_items").update(p).eq("id",state.editingShoppingId):state.supabase.from("shopping_items").insert({...p,created_by:state.user.id});const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#shoppingDialog");renderAll()}
async function toggleShopping(id){const x=state.shopping.find(y=>y.id===id);if(!x)return;if(!x.is_bought){let financeId=null;if(Number(x.estimated_price||0)>0){const f={board_id:state.board.id,entry_date:today(),title:`Compra: ${x.item_name}`,category:x.category||"🛒 Mercado",kind:"expense",amount:Number(x.estimated_price),is_paid:true,notes:x.quantity?`Quantidade: ${x.quantity}`:null,created_by:state.user.id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(state.mode==="demo"){financeId=crypto.randomUUID();state.finance.unshift({...f,id:financeId})}else{const r=await state.supabase.from("finance_entries").insert(f).select().single();if(r.error)return toast(r.error.message);financeId=r.data.id}}const patch={is_bought:true,bought_at:new Date().toISOString(),bought_by:state.user.id,finance_entry_id:financeId,updated_at:new Date().toISOString()};if(state.mode==="demo"){Object.assign(x,patch);demoSave()}else{await state.supabase.from("shopping_items").update(patch).eq("id",id);await refreshAll(false)}toast(financeId?"Comprado ✓ e lançado no Banquinho.":"Marcado como comprado.")}else{if(x.finance_entry_id){if(state.mode==="demo")state.finance=state.finance.filter(f=>f.id!==x.finance_entry_id);else await state.supabase.from("finance_entries").delete().eq("id",x.finance_entry_id)}const patch={is_bought:false,bought_at:null,bought_by:null,finance_entry_id:null,updated_at:new Date().toISOString()};if(state.mode==="demo"){Object.assign(x,patch);demoSave()}else{await state.supabase.from("shopping_items").update(patch).eq("id",id);await refreshAll(false)}}renderAll()}
async function deleteShopping(){const id=state.editingShoppingId;if(!id)return;const x=state.shopping.find(y=>y.id===id);if(x?.finance_entry_id){if(state.mode==="demo")state.finance=state.finance.filter(f=>f.id!==x.finance_entry_id);else await state.supabase.from("finance_entries").delete().eq("id",x.finance_entry_id)}if(state.mode==="demo"){state.shopping=state.shopping.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("shopping_items").delete().eq("id",id);await refreshAll(false)}closeDialog("#shoppingDialog");renderAll()}

function financeTotals(){const inc=state.finance.filter(x=>x.kind==="income"),exp=state.finance.filter(x=>x.kind==="expense"),received=inc.filter(x=>x.is_paid).reduce((a,x)=>a+Number(x.amount),0),spent=exp.filter(x=>x.is_paid).reduce((a,x)=>a+Number(x.amount),0),pending=exp.filter(x=>!x.is_paid).reduce((a,x)=>a+Number(x.amount),0);return{received,spent,pending,current:received-spent,projected:received-spent-pending}}
function monthKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`}
function billDueDate(b,base){const d=new Date(base.getFullYear(),base.getMonth(),1),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(Number(b.due_day),last));return isoDate(d)}
function billPayment(b,month){return state.billPayments.find(x=>x.bill_id===b.id&&x.billing_month===month)}
function billRowsAround(days=40){const rows=[],now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1);for(const b of state.bills.filter(x=>x.is_active!==false)){for(let i=0;i<3;i++){const m=addMonths(start,i),mk=monthKey(m);if(b.start_month&&mk<b.start_month)continue;if(b.end_month&&mk>b.end_month)continue;const due=billDueDate(b,m),diff=Math.round((parseDate(due)-parseDate(today()))/86400000),pay=billPayment(b,mk);if((diff>=-31&&diff<=days)||(!pay&&diff<0))rows.push({bill:b,month:mk,due,diff,payment:pay})}}return rows.sort((a,b)=>a.due.localeCompare(b.due))}
function dueLabel(r){if(r.payment)return{cls:"ok",text:"Pago"};if(r.diff<0)return{cls:"overdue",text:`Atrasada ${Math.abs(r.diff)}d`};if(r.diff===0)return{cls:"soon",text:"Vence hoje"};if(r.diff<=Number(r.bill.warning_days??3))return{cls:"soon",text:`Vence em ${r.diff}d`};return{cls:"",text:`Vence em ${r.diff}d`}}

function notifyDueBillsOnEntry(){
  if(state.billAlertShown)return;
  const rows=billRowsAround(7).filter(r=>!r.payment&&(r.diff<0||r.diff<=Number(r.bill.warning_days??3)));
  if(!rows.length)return;
  state.billAlertShown=true;
  const first=rows[0],label=dueLabel(first);
  toast(`💸 ${first.bill.title}: ${label.text}`);
  if("Notification" in window&&Notification.permission==="granted"){
    new Notification("Nosso Tempo 💸",{body:rows.length===1?`${first.bill.title}: ${label.text}`:`${rows.length} contas precisam de atenção.`});
  }
}
function renderFinance(){const t=financeTotals();$("#financeMetrics").innerHTML=[["💵","Entradas",money(t.received),"money"],["🧾","Gastos pagos",money(t.spent),"badish"],["⏳","Pendentes",money(t.pending),"warnish"],["✨","Sobra atual",money(t.current),t.current>=0?"goodish":"badish"]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");const allBillRows=billRowsAround(35),rows=state.bills.map(b=>allBillRows.find(r=>r.bill.id===b.id&&!r.payment)||allBillRows.find(r=>r.bill.id===b.id)).filter(Boolean);$("#billList").innerHTML=rows.length?rows.map(r=>{const l=dueLabel(r);return`<article class="list-card"><button class="circle-check ${r.payment?"checked":""}" data-bill-pay="${r.bill.id}" data-billing-month="${r.month}" data-due-date="${r.due}">${r.payment?"✓":""}</button><div class="list-card-main"><div class="list-card-title">${esc(r.bill.title)}</div><div class="list-card-meta"><span>${money(r.bill.amount)}</span><span>📅 dia ${r.bill.due_day}</span>${r.bill.responsible_to?`<span>👤 ${esc(memberName(r.bill.responsible_to))}</span>`:""}<span class="due-badge ${l.cls}">${l.text}</span></div></div><button class="icon-mini" data-edit-bill="${r.bill.id}">✎</button></article>`}).join(""):`<div class="empty-state">Nenhuma conta recorrente.</div>`;const f=$("#financeFilter")?.value||"all";let list=[...state.finance];if(f==="pending")list=list.filter(x=>!x.is_paid);if(f==="paid")list=list.filter(x=>x.is_paid);if(f==="expense")list=list.filter(x=>x.kind==="expense");if(f==="income")list=list.filter(x=>x.kind==="income");$("#financeList").innerHTML=list.length?list.map(x=>`<article class="list-card finance-row ${x.kind}"><button class="circle-check ${x.is_paid?"checked":""}" data-finance-paid="${x.id}">${x.is_paid?"✓":""}</button><div class="list-card-main"><div class="list-card-title">${esc(x.title)}</div><div class="list-card-meta"><span>${esc(x.category)}</span><span>📅 ${new Date(x.entry_date+"T12:00").toLocaleDateString("pt-BR")}</span></div></div><div class="amount">${x.kind==="income"?"+":"−"} ${money(x.amount)}</div><button class="icon-mini" data-edit-finance="${x.id}">✎</button></article>`).join(""):`<div class="empty-state">Sem movimentações.</div>`}
function openFinance(id=null){state.editingFinanceId=id;const x=id?state.finance.find(y=>y.id===id):null;$("#financeDialogTitle").textContent=x?"Editar lançamento":"Novo lançamento";$("#financeKind").value=x?.kind||"expense";$("#financeAmount").value=x?.amount||"";$("#financeTitle").value=x?.title||"";$("#financeCategory").value=x?.category||"🛒 Mercado";$("#financeDate").value=x?.entry_date||today();$("#financePaid").checked=!!x?.is_paid;$("#financeNotes").value=x?.notes||"";$("#deleteFinance").style.visibility=x?"visible":"hidden";openDialog("#financeDialog")}
async function saveFinance(e){e.preventDefault();const p={board_id:state.board.id,kind:$("#financeKind").value,amount:Number($("#financeAmount").value),title:$("#financeTitle").value.trim(),category:$("#financeCategory").value,entry_date:$("#financeDate").value,is_paid:$("#financePaid").checked,notes:$("#financeNotes").value.trim()||null,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingFinanceId)Object.assign(state.finance.find(x=>x.id===state.editingFinanceId),p);else state.finance.unshift({...p,id:crypto.randomUUID(),created_by:state.user.id,created_at:new Date().toISOString()});demoSave()}else{const q=state.editingFinanceId?state.supabase.from("finance_entries").update(p).eq("id",state.editingFinanceId):state.supabase.from("finance_entries").insert({...p,created_by:state.user.id});const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#financeDialog");renderAll()}
async function toggleFinance(id){const x=state.finance.find(y=>y.id===id);if(state.mode==="demo"){x.is_paid=!x.is_paid;demoSave()}else{await state.supabase.from("finance_entries").update({is_paid:!x.is_paid,updated_at:new Date().toISOString()}).eq("id",id);await refreshAll(false)}renderAll()}
async function deleteFinance(){const id=state.editingFinanceId;if(!id)return;if(state.mode==="demo"){state.finance=state.finance.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("finance_entries").delete().eq("id",id);await refreshAll(false)}closeDialog("#financeDialog");renderAll()}
function openBill(id=null){state.editingBillId=id;const b=id?state.bills.find(x=>x.id===id):null;$("#billDialogTitle").textContent=b?"Editar conta":"Nova conta";$("#billTitle").value=b?.title||"";$("#billAmount").value=b?.amount||"";$("#billDueDay").value=b?.due_day||"";$("#billCategory").value=b?.category||"💡 Contas";$("#billResponsible").value=b?.responsible_to||"";$("#billStartMonth").value=b?.start_month?b.start_month.slice(0,7):today().slice(0,7);$("#billEndMonth").value=b?.end_month?b.end_month.slice(0,7):"";$("#billWarningDays").value=b?.warning_days??3;$("#billNotes").value=b?.notes||"";$("#deleteBill").style.visibility=b?"visible":"hidden";openDialog("#billDialog")}
async function saveBill(e){e.preventDefault();const sm=$("#billStartMonth").value||today().slice(0,7),em=$("#billEndMonth").value,p={board_id:state.board.id,title:$("#billTitle").value.trim(),amount:Number($("#billAmount").value),due_day:Number($("#billDueDay").value),category:$("#billCategory").value,responsible_to:$("#billResponsible").value||null,start_month:`${sm}-01`,end_month:em?`${em}-01`:null,warning_days:Number($("#billWarningDays").value||3),notes:$("#billNotes").value.trim()||null,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingBillId)Object.assign(state.bills.find(x=>x.id===state.editingBillId),p);else state.bills.push({...p,id:crypto.randomUUID(),is_active:true,created_by:state.user.id,created_at:new Date().toISOString()});demoSave()}else{const q=state.editingBillId?state.supabase.from("recurring_bills").update(p).eq("id",state.editingBillId):state.supabase.from("recurring_bills").insert({...p,created_by:state.user.id});const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#billDialog");renderAll()}
async function toggleBillPayment(billId,month,due){const b=state.bills.find(x=>x.id===billId),pay=billPayment(b,month);if(pay){if(pay.finance_entry_id){if(state.mode==="demo")state.finance=state.finance.filter(x=>x.id!==pay.finance_entry_id);else await state.supabase.from("finance_entries").delete().eq("id",pay.finance_entry_id)}if(state.mode==="demo"){state.billPayments=state.billPayments.filter(x=>x.id!==pay.id);demoSave()}else{await state.supabase.from("recurring_bill_payments").delete().eq("id",pay.id);await refreshAll(false)}toast("Pagamento desmarcado.")}else{let financeId=null;const f={board_id:state.board.id,entry_date:due,title:b.title,category:b.category,kind:"expense",amount:Number(b.amount),is_paid:true,notes:"Conta recorrente",created_by:state.user.id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(state.mode==="demo"){financeId=crypto.randomUUID();state.finance.unshift({...f,id:financeId});state.billPayments.push({id:crypto.randomUUID(),board_id:state.board.id,bill_id:billId,billing_month:month,due_date:due,amount:b.amount,finance_entry_id:financeId,paid_by:state.user.id,paid_at:new Date().toISOString()});demoSave()}else{const fr=await state.supabase.from("finance_entries").insert(f).select().single();if(fr.error)return toast(fr.error.message);financeId=fr.data.id;await state.supabase.from("recurring_bill_payments").insert({board_id:state.board.id,bill_id:billId,billing_month:month,due_date:due,amount:b.amount,finance_entry_id:financeId,paid_by:state.user.id});await refreshAll(false)}toast("Conta paga ✓ e lançada no Banquinho.")}renderAll()}
async function deleteBill(){const id=state.editingBillId;if(!id)return;if(state.mode==="demo"){state.bills=state.bills.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("recurring_bills").delete().eq("id",id);await refreshAll(false)}closeDialog("#billDialog");renderAll()}

function petTaskTypes(p,date){return[...new Set([...PET_DEFAULT_TASKS,...state.petLogs.filter(x=>x.pet_id===p.id&&x.care_date===date).map(x=>x.task_type)])]}
function petLog(pid,date,type){return state.petLogs.find(x=>x.pet_id===pid&&x.care_date===date&&x.task_type===type)}
function healthTypeLabel(t){return({vaccine:"💉 Vacina",dewormer:"💊 Vermífugo",flea:"🪲 Antipulgas",vet:"🩺 Veterinário",weight:"⚖️ Peso",medicine:"💊 Medicamento",other:"✨ Outro"})[t]||t}
function renderPets(){const date=$("#petDate").value||today();$("#petDate").value=date;const done=state.pets.reduce((a,p)=>a+PET_DEFAULT_TASKS.filter(t=>petLog(p.id,date,t)?.is_done).length,0),expected=state.pets.length*PET_DEFAULT_TASKS.length,dueHealth=state.petHealth.filter(x=>x.next_due_date&&x.next_due_date<=isoDate(addDays(new Date(),30))).length;$("#petMetrics").innerHTML=[["🐾","Cuidados hoje",`${done}/${expected}`,"goodish"],["🐱","Pets",state.pets.length,""],["🩺","Saúde próxima",dueHealth,"warnish"],["💛","Meta","constância",""]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");$("#petGrid").innerHTML=state.pets.map(p=>`<article class="pet-card"><div class="pet-head"><div class="pet-avatar">${p.emoji||"🐱"}</div><div><h3>${esc(p.name)}</h3><small>${esc(p.species)} • ${esc(p.coat||"")}</small></div></div><div class="pet-care-list">${petTaskTypes(p,date).map(type=>{const l=petLog(p.id,date,type);return`<button class="care-toggle ${l?.is_done?"done":""}" data-pet-care="${p.id}" data-care-type="${esc(type)}">${l?.is_done?"✓ ":""}${esc(type)}</button>`}).join("")}</div><div class="pet-add-care"><input data-pet-custom-input="${p.id}" placeholder="Outro cuidado..."/><button class="btn secondary" data-add-pet-care="${p.id}">+</button></div></article>`).join("");const health=[...state.petHealth].sort((a,b)=>(a.next_due_date||"9999").localeCompare(b.next_due_date||"9999"));$("#petHealthList").innerHTML=health.length?health.map(h=>{const pet=state.pets.find(x=>x.id===h.pet_id),due=h.next_due_date,cls=due&&due<today()?"health-due":due&&due<=isoDate(addDays(new Date(),30))?"health-upcoming":"";return`<article class="list-card ${cls}"><div class="list-card-main"><div class="list-card-title">${esc(pet?.name||"Pet")} • ${healthTypeLabel(h.record_type)} • ${esc(h.title)}</div><div class="list-card-meta"><span>Feito: ${new Date(h.record_date+"T12:00").toLocaleDateString("pt-BR")}</span>${due?`<span>Próximo: ${new Date(due+"T12:00").toLocaleDateString("pt-BR")}</span>`:""}${h.weight_kg?`<span>⚖️ ${h.weight_kg} kg</span>`:""}</div></div><button class="icon-mini" data-edit-health="${h.id}">✎</button></article>`}).join(""):`<div class="empty-state">Nenhum registro de saúde.</div>`}
async function togglePetCare(pid,type){const date=$("#petDate").value,l=petLog(pid,date,type),next=!l?.is_done;if(state.mode==="demo"){if(l)l.is_done=next;else state.petLogs.push({id:crypto.randomUUID(),pet_id:pid,care_date:date,task_type:type,is_done:true,done_by:state.user.id});demoSave()}else{if(l)await state.supabase.from("pet_care_logs").update({is_done:next,done_by:next?state.user.id:null,done_at:next?new Date().toISOString():null}).eq("id",l.id);else await state.supabase.from("pet_care_logs").insert({board_id:state.board.id,pet_id:pid,care_date:date,task_type:type,is_done:true,done_by:state.user.id,done_at:new Date().toISOString()});await refreshAll(false)}renderAll()}
async function addCustomPetCare(pid){const input=$(`[data-pet-custom-input="${pid}"]`),type=input.value.trim();if(!type)return;const date=$("#petDate").value;if(state.mode==="demo"){state.petLogs.push({id:crypto.randomUUID(),pet_id:pid,care_date:date,task_type:type,is_done:false});demoSave()}else{await state.supabase.from("pet_care_logs").upsert({board_id:state.board.id,pet_id:pid,care_date:date,task_type:type,is_done:false},{onConflict:"pet_id,care_date,task_type"});await refreshAll(false)}input.value="";renderPets()}
function openHealth(id=null){state.editingHealthId=id;const h=id?state.petHealth.find(x=>x.id===id):null;$("#petHealthDialogTitle").textContent=h?"Editar registro":"Novo registro";$("#healthPet").value=h?.pet_id||state.pets[0]?.id||"";$("#healthType").value=h?.record_type||"vaccine";$("#healthTitle").value=h?.title||"";$("#healthDate").value=h?.record_date||today();$("#healthNextDate").value=h?.next_due_date||"";$("#healthWeight").value=h?.weight_kg??"";$("#healthDose").value=h?.dosage||"";$("#healthNotes").value=h?.notes||"";$("#deletePetHealth").style.visibility=h?"visible":"hidden";openDialog("#petHealthDialog")}
async function saveHealth(e){e.preventDefault();const p={board_id:state.board.id,pet_id:$("#healthPet").value,record_type:$("#healthType").value,title:$("#healthTitle").value.trim(),record_date:$("#healthDate").value,next_due_date:$("#healthNextDate").value||null,weight_kg:$("#healthWeight").value?Number($("#healthWeight").value):null,dosage:$("#healthDose").value.trim()||null,notes:$("#healthNotes").value.trim()||null,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingHealthId)Object.assign(state.petHealth.find(x=>x.id===state.editingHealthId),p);else state.petHealth.push({...p,id:crypto.randomUUID(),created_by:state.user.id,created_at:new Date().toISOString()});demoSave()}else{const q=state.editingHealthId?state.supabase.from("pet_health_records").update(p).eq("id",state.editingHealthId):state.supabase.from("pet_health_records").insert({...p,created_by:state.user.id});const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#petHealthDialog");renderAll()}
async function deleteHealth(){const id=state.editingHealthId;if(!id)return;if(state.mode==="demo"){state.petHealth=state.petHealth.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("pet_health_records").delete().eq("id",id);await refreshAll(false)}closeDialog("#petHealthDialog");renderAll()}

function renderGoals(){const active=state.goals.filter(g=>g.status==="active"),completed=state.goals.filter(g=>g.status==="completed");$("#goalMetrics").innerHTML=[["🎯","Ativas",active.length,""],["✅","Concluídas",completed.length,"goodish"],["⏳","Com prazo",active.filter(g=>g.deadline).length,"warnish"],["💰","Financeiras",active.filter(g=>g.goal_type==="money").length,"money"]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");$("#goalGrid").innerHTML=state.goals.length?state.goals.map(g=>{const pct=Math.min(100,Math.round(Number(g.current_value)/Number(g.target_value)*100)),unit=g.goal_type==="money"?"R$":g.unit||"";return`<article class="goal-card"><div class="goal-top"><div><p class="eyebrow">${g.status==="completed"?"CONCLUÍDA":"META"}</p><h3>${esc(g.title)}</h3></div><strong>${pct}%</strong></div><div class="goal-progress"><i style="width:${pct}%"></i></div><div class="list-card-meta"><span>${g.goal_type==="money"?money(g.current_value):`${g.current_value} ${esc(unit)}`} / ${g.goal_type==="money"?money(g.target_value):`${g.target_value} ${esc(unit)}`}</span>${g.deadline?`<span>📅 ${new Date(g.deadline+"T12:00").toLocaleDateString("pt-BR")}</span>`:""}</div><div class="goal-actions"><div class="progress-inline"><input type="number" step="0.01" min="0" placeholder="+ progresso" data-goal-add-input="${g.id}"/><button class="btn secondary" data-goal-add="${g.id}">Adicionar</button></div><button class="icon-mini" data-edit-goal="${g.id}">✎</button></div></article>`}).join(""):`<div class="empty-state">Nenhuma meta criada.</div>`}
function openGoal(id=null){state.editingGoalId=id;const g=id?state.goals.find(x=>x.id===id):null;$("#goalDialogTitle").textContent=g?"Editar meta":"Nova meta";$("#goalTitle").value=g?.title||"";$("#goalType").value=g?.goal_type||"money";$("#goalUnit").value=g?.unit||"";$("#goalCurrent").value=g?.current_value??0;$("#goalTarget").value=g?.target_value||"";$("#goalDeadline").value=g?.deadline||"";$("#goalNotes").value=g?.notes||"";$("#deleteGoal").style.visibility=g?"visible":"hidden";openDialog("#goalDialog")}
async function saveGoal(e){e.preventDefault();const current=Number($("#goalCurrent").value||0),target=Number($("#goalTarget").value),p={board_id:state.board.id,title:$("#goalTitle").value.trim(),goal_type:$("#goalType").value,unit:$("#goalUnit").value.trim()||null,current_value:current,target_value:target,deadline:$("#goalDeadline").value||null,notes:$("#goalNotes").value.trim()||null,status:current>=target?"completed":"active",updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingGoalId)Object.assign(state.goals.find(x=>x.id===state.editingGoalId),p);else state.goals.push({...p,id:crypto.randomUUID(),created_by:state.user.id,created_at:new Date().toISOString()});demoSave()}else{const q=state.editingGoalId?state.supabase.from("goals").update(p).eq("id",state.editingGoalId):state.supabase.from("goals").insert({...p,created_by:state.user.id});const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#goalDialog");renderAll()}
async function addGoalProgress(id){const input=$(`[data-goal-add-input="${id}"]`),add=Number(input.value||0),g=state.goals.find(x=>x.id===id);if(!add)return;const next=Number(g.current_value)+add,patch={current_value:next,status:next>=Number(g.target_value)?"completed":"active",updated_at:new Date().toISOString()};if(state.mode==="demo"){Object.assign(g,patch);demoSave()}else{await state.supabase.from("goals").update(patch).eq("id",id);await refreshAll(false)}renderAll()}
async function deleteGoal(){const id=state.editingGoalId;if(!id)return;if(state.mode==="demo"){state.goals=state.goals.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("goals").delete().eq("id",id);await refreshAll(false)}closeDialog("#goalDialog");renderAll()}

function renderStock(){const low=state.stock.filter(x=>Number(x.current_qty)<=Number(x.min_qty));$("#stockMetrics").innerHTML=[["⚠️","Acabando",low.length,low.length?"badish":"goodish"],["📦","Itens",state.stock.length,""],["🛒","Podem virar compra",low.length,"warnish"],["✅","Estoque ok",state.stock.length-low.length,"goodish"]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");$("#stockList").innerHTML=state.stock.length?state.stock.map(x=>{const low=Number(x.current_qty)<=Number(x.min_qty);return`<article class="list-card ${low?"stock-low":"stock-ok"}"><div class="list-card-main"><div class="list-card-title">${esc(x.item_name)}</div><div class="list-card-meta"><span>${esc(x.category)}</span><span class="stock-qty">${x.current_qty} ${esc(x.unit||"")}</span><span>mínimo ${x.min_qty} ${esc(x.unit||"")}</span>${low?`<span class="warning-text">⚠️ Está acabando</span>`:""}</div></div>${low?`<button class="btn secondary compact" data-stock-to-shopping="${x.id}">🛒 Comprar</button>`:""}<button class="icon-mini" data-edit-stock="${x.id}">✎</button></article>`}).join(""):`<div class="empty-state">Nenhum item no estoque.</div>`}
function openStock(id=null){state.editingStockId=id;const x=id?state.stock.find(y=>y.id===id):null;$("#stockDialogTitle").textContent=x?"Editar item":"Novo item";$("#stockName").value=x?.item_name||"";$("#stockCategory").value=x?.category||"✨ Outro";$("#stockUnit").value=x?.unit||"";$("#stockCurrent").value=x?.current_qty??"";$("#stockMin").value=x?.min_qty??"";$("#stockNotes").value=x?.notes||"";$("#deleteStock").style.visibility=x?"visible":"hidden";openDialog("#stockDialog")}
async function saveStock(e){e.preventDefault();const p={board_id:state.board.id,item_name:$("#stockName").value.trim(),category:$("#stockCategory").value,unit:$("#stockUnit").value.trim()||null,current_qty:Number($("#stockCurrent").value),min_qty:Number($("#stockMin").value),notes:$("#stockNotes").value.trim()||null,updated_by:state.user.id,updated_at:new Date().toISOString()};if(state.mode==="demo"){if(state.editingStockId)Object.assign(state.stock.find(x=>x.id===state.editingStockId),p);else state.stock.push({...p,id:crypto.randomUUID(),created_at:new Date().toISOString()});demoSave()}else{const q=state.editingStockId?state.supabase.from("inventory_items").update(p).eq("id",state.editingStockId):state.supabase.from("inventory_items").insert(p);const{error}=await q;if(error)return toast(error.message);await refreshAll(false)}closeDialog("#stockDialog");renderAll()}
async function stockToShopping(id){const x=state.stock.find(y=>y.id===id);if(state.shopping.some(s=>!s.is_bought&&s.item_name.toLowerCase()===x.item_name.toLowerCase()))return toast("Esse item já está na lista.");const p={board_id:state.board.id,item_name:x.item_name,quantity:`repor ${x.unit||""}`.trim(),category:x.category.includes("Pets")?"🐾 Pets":"🛒 Mercado",assigned_to:null,estimated_price:null,notes:`Estoque baixo: ${x.current_qty} ${x.unit||""}`,is_bought:false,created_by:state.user.id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(state.mode==="demo"){state.shopping.unshift({...p,id:crypto.randomUUID()});demoSave()}else{await state.supabase.from("shopping_items").insert(p);await refreshAll(false)}toast("Adicionado à lista de compras 🛒");renderAll()}
async function deleteStock(){const id=state.editingStockId;if(!id)return;if(state.mode==="demo"){state.stock=state.stock.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("inventory_items").delete().eq("id",id);await refreshAll(false)}closeDialog("#stockDialog");renderAll()}

function isNoticeRead(id){return state.noticeReads.some(x=>x.notice_id===id&&x.user_id===state.user.id)}
function activeNotices(){return state.notices.filter(n=>!n.expires_at||n.expires_at>=today())}
function unreadNotices(){return activeNotices().filter(n=>n.created_by!==state.user.id&&!isNoticeRead(n.id))}
function renderNotices(){const list=activeNotices();$("#noticeList").innerHTML=list.length?list.map(n=>`<article class="notice-card ${n.priority==="important"?"important":""} ${!isNoticeRead(n.id)&&n.created_by!==state.user.id?"unread":""}"><p class="eyebrow">${n.priority==="important"?"IMPORTANTE":"RECADO"}</p><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><div class="notice-meta"><span>por ${esc(memberName(n.created_by))}</span>${n.created_by!==state.user.id&&!isNoticeRead(n.id)?`<button class="small-btn" data-read-notice="${n.id}">Marcar lido</button>`:""}</div></article>`).join(""):`<div class="empty-state">Nenhum recado.</div>`;const u=unreadNotices().length;$("#noticeBadge").textContent=u;$("#noticeBadge").classList.toggle("hidden",!u)}
function openNotice(){$("#noticeForm").reset();openDialog("#noticeDialog")}
async function saveNotice(e){e.preventDefault();const p={board_id:state.board.id,title:$("#noticeTitle").value.trim(),body:$("#noticeBody").value.trim(),priority:$("#noticePriority").value,expires_at:$("#noticeExpires").value||null,created_by:state.user.id};if(state.mode==="demo"){state.notices.unshift({...p,id:crypto.randomUUID(),created_at:new Date().toISOString()});demoSave()}else{await state.supabase.from("notices").insert(p);await refreshAll(false)}closeDialog("#noticeDialog");renderAll()}
async function markNoticeRead(id){if(state.mode==="demo"){if(!isNoticeRead(id))state.noticeReads.push({notice_id:id,user_id:state.user.id,read_at:new Date().toISOString()});demoSave()}else{await state.supabase.from("notice_reads").upsert({board_id:state.board.id,notice_id:id,user_id:state.user.id,read_at:new Date().toISOString()},{onConflict:"notice_id,user_id"});await refreshAll(false)}renderAll()}
function showUnreadNotices(){const list=unreadNotices();if(!list.length)return;$("#unreadNoticeList").innerHTML=list.map(n=>`<article class="notice-card ${n.priority==="important"?"important":""}"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><small class="muted">por ${esc(memberName(n.created_by))}</small></article>`).join("");openDialog("#unreadDialog")}
async function markAllNoticesRead(){for(const n of unreadNotices())await markNoticeRead(n.id);closeDialog("#unreadDialog")}

function todayAvailabilityRows(){const d=today(),wd=parseDate(d).getDay();return state.members.map(m=>({member:m,blocks:state.availability.filter(b=>b.user_id===m.user_id&&(b.specific_date===d||(!b.specific_date&&Number(b.weekday)===wd)))}))}
function renderToday(){const date=today();$("#todayDateTitle").textContent=new Date(date+"T12:00").toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});const plans=plansOn(date),tasks=taskInstances(date,date),petDone=state.pets.reduce((a,p)=>a+PET_DEFAULT_TASKS.filter(t=>petLog(p.id,date,t)?.is_done).length,0),petExpected=state.pets.length*PET_DEFAULT_TASKS.length,bills=billRowsAround(7).filter(r=>!r.payment&&(r.diff<=Number(r.bill.warning_days??3)||r.diff<0)),unread=unreadNotices().length,low=state.stock.filter(x=>Number(x.current_qty)<=Number(x.min_qty)).length;$("#todayMetrics").innerHTML=[["📅","Atividades",plans.length,""],["✅","Rotinas/tarefas",tasks.length,""],["🐾","Pets",`${petDone}/${petExpected}`,"goodish"],["💸","Contas alertando",bills.length,bills.length?"warnish":"goodish"],["💌","Recados",unread,unread?"warnish":""],["📦","Estoque baixo",low,low?"badish":"goodish"]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");
$("#todayPlans").innerHTML=plans.length?plans.map(p=>`<article class="list-card"><button class="circle-check ${effectivePlanStatus(p)==="done"?"checked":""}" data-today-plan="${p.id}">${effectivePlanStatus(p)==="done"?"✓":""}</button><div class="list-card-main"><div class="list-card-title">${esc(p.title)}</div><div class="list-card-meta"><span>${p.start_time?String(p.start_time).slice(0,5):"sem hora"}${p.end_time?`–${String(p.end_time).slice(0,5)}`:""}</span></div></div></article>`).join(""):`<div class="empty-state">Nada marcado.</div>`;
$("#todayTasks").innerHTML=tasks.length?tasks.map(r=>`<article class="list-card"><button class="circle-check ${r.status==="done"?"checked":r.status==="unexpected"?"unexpected":""}" data-today-task="${r.task.id}" data-occurrence-date="${r.date}">${r.status==="done"?"✓":r.status==="unexpected"?"⚡":""}</button><div class="list-card-main"><div class="list-card-title">${esc(r.task.title)}</div><div class="list-card-meta">${isRecurringTask(r.task)?`<span>🔁 ${esc(recurrenceText(r.task))}</span>`:""}${r.task.assigned_to?`<span>👤 ${esc(memberName(r.task.assigned_to))}</span>`:""}</div></div></article>`).join(""):`<div class="empty-state">Nenhuma rotina para hoje.</div>`;
$("#todayPets").innerHTML=state.pets.length?state.pets.map(p=>{const d=PET_DEFAULT_TASKS.filter(t=>petLog(p.id,date,t)?.is_done).length;return`<div class="breakdown-row"><span>${p.emoji||"🐱"} ${esc(p.name)}</span><strong>${d}/${PET_DEFAULT_TASKS.length}</strong></div>`}).join(""):`<div class="empty-state">Sem pets.</div>`;
$("#todayBills").innerHTML=bills.length?bills.slice(0,6).map(r=>{const l=dueLabel(r);return`<article class="list-card"><div class="list-card-main"><div class="list-card-title">${esc(r.bill.title)}</div><div class="list-card-meta"><span>${money(r.bill.amount)}</span><span class="due-badge ${l.cls}">${l.text}</span></div></div><button class="circle-check" data-bill-pay="${r.bill.id}" data-billing-month="${r.month}" data-due-date="${r.due}"></button></article>`}).join(""):`<div class="empty-state">Nenhuma conta pedindo atenção.</div>`;
$("#todayAvailability").innerHTML=todayAvailabilityRows().map(r=>`<article class="list-card"><span class="member-color" style="background:${r.member.profile_color||"#df8f7c"}"></span><div class="list-card-main"><div class="list-card-title">${esc(r.member.display_name)}</div><div class="list-card-meta">${r.blocks.length?r.blocks.map(b=>`<span>${b.availability_type==="busy"?"🔴":"🟢"} ${String(b.start_time).slice(0,5)}–${String(b.end_time).slice(0,5)} ${esc(b.label)}</span>`).join(""):`<span>⚪ Sem horários cadastrados hoje</span>`}</div></div></article>`).join("");
const alerts=[];state.stock.filter(x=>Number(x.current_qty)<=Number(x.min_qty)).slice(0,4).forEach(x=>alerts.push(`📦 ${x.item_name} está acabando`));state.petHealth.filter(x=>x.next_due_date&&x.next_due_date<=isoDate(addDays(new Date(),7))).slice(0,3).forEach(x=>alerts.push(`🐾 ${state.pets.find(p=>p.id===x.pet_id)?.name||"Pet"}: ${x.title} em ${new Date(x.next_due_date+"T12:00").toLocaleDateString("pt-BR")}`));state.goals.filter(g=>g.status==="active"&&g.deadline&&g.deadline<=isoDate(addDays(new Date(),7))).slice(0,2).forEach(g=>alerts.push(`🎯 Meta "${g.title}" perto do prazo`));$("#todayAlerts").innerHTML=alerts.length?alerts.map(a=>`<article class="list-card"><div class="list-card-main">${esc(a)}</div></article>`).join(""):`<div class="empty-state">Sem alertas importantes.</div>`}

function renderSummary(){const pc={done:0,missed:0,unexpected:0,planned:0};state.plans.filter(p=>inRange(p.plan_date)).forEach(p=>pc[effectivePlanStatus(p)]++);const from=isoDate(addDays(new Date(),-30)),tc={done:0,missed:0,unexpected:0,planned:0};taskInstances(from,today()).forEach(x=>tc[x.status]++);const ft=financeTotals(),petExpected=state.pets.length*PET_DEFAULT_TASKS.length*7,petDone=state.petLogs.filter(x=>x.care_date>=isoDate(addDays(new Date(),-6))&&x.care_date<=today()&&PET_DEFAULT_TASKS.includes(x.task_type)&&x.is_done).length,ar=pc.done+pc.missed?Math.round(pc.done/(pc.done+pc.missed)*100):100,tr=tc.done+tc.missed?Math.round(tc.done/(tc.done+tc.missed)*100):100,pr=petExpected?Math.round(petDone/petExpected*100):0;$("#summaryMetrics").innerHTML=[["✅","Atividades feitas",pc.done,"goodish"],["○","Não realizadas",pc.missed,"badish"],["🎯","Metas concluídas",state.goals.filter(g=>g.status==="completed").length,"goodish"],["📦","Estoque baixo",state.stock.filter(x=>Number(x.current_qty)<=Number(x.min_qty)).length,"warnish"]].map(x=>`<article class="metric-card ${x[3]}"><strong>${x[0]} ${x[2]}</strong><small>${x[1]}</small></article>`).join("");$("#activityRate").textContent=`${ar}%`;$("#activityProgress").style.width=`${ar}%`;$("#activityBreakdown").innerHTML=breakdown([["Realizados",pc.done],["Não realizados",pc.missed],["Imprevistos",pc.unexpected],["Planejados",pc.planned]]);$("#taskRate").textContent=`${tr}%`;$("#taskProgress").style.width=`${tr}%`;$("#taskBreakdown").innerHTML=breakdown([["Realizadas • 30d",tc.done],["Não realizadas",tc.missed],["Imprevistos",tc.unexpected],["Rotinas",state.tasks.filter(isRecurringTask).length]]);$("#petRate").textContent=`${pr}%`;$("#petProgress").style.width=`${pr}%`;$("#petBreakdown").innerHTML=breakdown([["Cuidados marcados",petDone],["Cuidados esperados",petExpected],["Registros de saúde",state.petHealth.length]]);$("#financeBreakdown").innerHTML=breakdown([["Entradas",money(ft.received)],["Gastos",money(ft.spent)],["Sobra atual",money(ft.current)],["Compras pendentes",state.shopping.filter(x=>!x.is_bought).length],["Contas recorrentes",state.bills.length],["Estoque baixo",state.stock.filter(x=>Number(x.current_qty)<=Number(x.min_qty)).length]])}
function breakdown(rows){return rows.map(([a,b])=>`<div class="breakdown-row"><span class="muted">${a}</span><strong>${b}</strong></div>`).join("")}

function renderProfile(){const me=state.members.find(m=>m.user_id===state.user?.id);if(me){$("#profileName").value=me.display_name||"";$("#profileColor").value=me.profile_color||"#df8f7c";$("#profileNote").value=me.profile_note||""}const mine=state.availability.filter(x=>x.user_id===state.user?.id);$("#availabilityList").innerHTML=mine.length?mine.map(b=>`<div class="availability-row ${b.availability_type}"><div class="availability-copy"><strong>${b.specific_date?new Date(b.specific_date+"T12:00").toLocaleDateString("pt-BR"):WEEKDAYS[b.weekday]}</strong> • ${String(b.start_time).slice(0,5)}–${String(b.end_time).slice(0,5)}<br><small class="muted">${b.availability_type==="busy"?"Ocupado":"Disponível"}: ${esc(b.label)}</small></div><button class="icon-mini" data-delete-availability="${b.id}">×</button></div>`).join(""):`<p class="muted tiny">Nenhum horário.</p>`;$("#memberProfiles").innerHTML=state.members.map(m=>`<article class="member-profile"><div class="member-name-line"><span class="member-color" style="background:${m.profile_color||"#df8f7c"}"></span>${esc(m.display_name)}</div><p class="muted tiny">${esc(m.profile_note||"Sem recado.")}</p></article>`).join("")}
async function saveProfile(e){e.preventDefault();const n=$("#profileName").value.trim(),c=$("#profileColor").value,note=$("#profileNote").value.trim();if(state.mode==="demo"){Object.assign(state.members.find(m=>m.user_id===state.user.id),{display_name:n,profile_color:c,profile_note:note});demoSave()}else{await state.supabase.rpc("update_my_profile",{p_board_id:state.board.id,p_display_name:n,p_profile_color:c,p_profile_note:note});await refreshAll(false)}renderAll()}
async function saveAvailability(e){e.preventDefault();const p={board_id:state.board.id,user_id:state.user.id,weekday:Number($("#availabilityWeekday").value),specific_date:$("#availabilityDate").value||null,start_time:$("#availabilityStart").value,end_time:$("#availabilityEnd").value,availability_type:$("#availabilityType").value,label:$("#availabilityLabel").value.trim()};if(p.end_time<=p.start_time)return toast("Horário final precisa ser depois.");if(state.mode==="demo"){state.availability.push({...p,id:crypto.randomUUID()});demoSave()}else{await state.supabase.from("availability_blocks").insert(p);await refreshAll(false)}$("#availabilityLabel").value="";renderAll()}
async function deleteAvailability(id){if(state.mode==="demo"){state.availability=state.availability.filter(x=>x.id!==id);demoSave()}else{await state.supabase.from("availability_blocks").delete().eq("id",id);await refreshAll(false)}renderAll()}

function renderAll(){renderMemberSelects();renderCalendar();renderTasks();renderShopping();renderFinance();renderPets();renderGoals();renderStock();renderNotices();renderSummary();renderProfile();renderToday()}
function setPage(page){state.page=page;$$("[data-app-page]").forEach(x=>x.classList.toggle("active",x.dataset.appPage===page));$$("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#mobileFab").classList.toggle("hidden",page!=="calendar");if(page==="today")renderToday();window.scrollTo({top:0,behavior:"smooth"})}
async function applyRange(s,e){if(!s||!e||s>e)return toast("Escolha um período válido.");state.rangeStart=s;state.rangeEnd=e;$("#startDate").value=s;$("#endDate").value=e;renderCalendar();renderSummary();await loadWeather()}
function downloadICS(){const date=state.activeDate.replaceAll("-",""),start=($("#planTime").value||"19:00").replace(":","")+"00",end=($("#planEndTime").value||$("#planTime").value||"20:00").replace(":","")+"00",title=($("#planTitle").value||"Nosso Tempo").replace(/,/g,"\\,"),ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Nosso Tempo//PT-BR","BEGIN:VEVENT",`UID:${crypto.randomUUID()}@nosso-tempo`,`DTSTART;TZID=America/Sao_Paulo:${date}T${start}`,`DTEND;TZID=America/Sao_Paulo:${date}T${end}`,`SUMMARY:${title}`,"BEGIN:VALARM","TRIGGER:-PT30M","ACTION:DISPLAY","DESCRIPTION:Lembrete Nosso Tempo","END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n"),blob=new Blob([ics],{type:"text/calendar"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`nosso-tempo-${state.activeDate}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function requestNotifications(){if(!("Notification"in window))return toast("Navegador sem suporte.");const r=await Notification.requestPermission();toast(r==="granted"?"Notificações ativadas.":"Não autorizadas.")}

function bindEvents(){
$$(".tab").forEach(b=>b.addEventListener("click",()=>{state.authMode=b.dataset.authTab;$$(".tab").forEach(x=>x.classList.toggle("active",x===b));$("#authSubmit").textContent=state.authMode==="login"?"Entrar":"Criar conta"}));
$("#authForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(state.authMode==="signup"){const{data,error}=await state.supabase.auth.signUp({email,password});if(error)return toast(error.message);if(!data.session)return toast("Conta criada. Confirme o e-mail.");state.user=data.user}else{const{data,error}=await state.supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);state.user=data.user}await loadBoards()});
$("#createBoardForm").addEventListener("submit",async e=>{e.preventDefault();const{error}=await state.supabase.rpc("create_board",{p_name:$("#boardName").value.trim(),p_display_name:$("#creatorName").value.trim()});if(error)return toast(error.message);await loadBoards()});
$("#joinBoardForm").addEventListener("submit",async e=>{e.preventDefault();const{error}=await state.supabase.rpc("join_board",{p_join_code:$("#joinCode").value.trim(),p_display_name:$("#joinName").value.trim()});if(error)return toast(error.message);await loadBoards()});
$("#existingBoards").addEventListener("click",async e=>{const b=e.target.closest("[data-board-id]");if(b)await selectBoard(state.boards.find(x=>x.id===b.dataset.boardId))});
$("#boardLogout").addEventListener("click",async()=>{await state.supabase?.auth.signOut();showOnly("#authScreen")});
$("#appNav").addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)setPage(b.dataset.page)});
document.body.addEventListener("click",e=>{const g=e.target.closest("[data-goto]");if(g)setPage(g.dataset.goto)});
$("#calendarGrid").addEventListener("click",e=>{const p=e.target.closest("[data-plan-id]");if(p){e.stopPropagation();return openPlan(p.dataset.planId)}const d=e.target.closest(".day-card");if(d)openDay(d.dataset.date)});
$("#dayPlanList").addEventListener("click",e=>{const p=e.target.closest("[data-edit-plan]");if(p)return openPlan(p.dataset.editPlan);const q=e.target.closest("[data-quick-plan]");if(q)return quickPlan(q.dataset.quickPlan)});
$("#addPlanForDay").addEventListener("click",()=>openPlan(null,state.activeDate));$("#mobileFab").addEventListener("click",()=>openDay(inRange(today())?today():state.rangeStart));$("#planForm").addEventListener("submit",savePlan);$("#closePlanDialog").addEventListener("click",()=>closeDialog("#planDialog"));$("#deletePlan").addEventListener("click",deletePlan);$("#downloadICS").addEventListener("click",downloadICS);$("#planTime").addEventListener("change",updateAvailabilityWarning);$("#planEndTime").addEventListener("change",updateAvailabilityWarning);$("#participantChecks").addEventListener("change",updateAvailabilityWarning);
$("#activityUnexpected").addEventListener("change",()=>{$("#incidentReasonWrap").classList.toggle("hidden",!$("#activityUnexpected").checked);if($("#activityUnexpected").checked)$("#activityDone").checked=false});$("#activityDone").addEventListener("change",()=>{if($("#activityDone").checked)$("#activityUnexpected").checked=false;$("#incidentReasonWrap").classList.add("hidden")});
$("#addPlanChecklistItem").addEventListener("click",()=>{const v=$("#newPlanChecklistText").value.trim();if(!v)return;state.editChecklist.push({item_text:v,is_done:false});$("#newPlanChecklistText").value="";renderPlanChecklist()});$("#planChecklistList").addEventListener("click",e=>{const r=e.target.closest("[data-remove-plan-check]");if(r){state.editChecklist.splice(Number(r.dataset.removePlanCheck),1);renderPlanChecklist()}});$("#planChecklistList").addEventListener("change",e=>{if(e.target.matches("[data-plan-check]"))state.editChecklist[Number(e.target.dataset.planCheck)].is_done=e.target.checked});
$("#applyRange").addEventListener("click",()=>applyRange($("#startDate").value,$("#endDate").value));$("#prevPeriod").addEventListener("click",()=>applyRange(isoDate(addMonths(parseDate(state.rangeStart),-1)),isoDate(addMonths(parseDate(state.rangeEnd),-1))));$("#nextPeriod").addEventListener("click",()=>applyRange(isoDate(addMonths(parseDate(state.rangeStart),1)),isoDate(addMonths(parseDate(state.rangeEnd),1))));$("#todayButton").addEventListener("click",()=>applyRange(today(),isoDate(addMonths(new Date(),1))));
$("#newTaskButton").addEventListener("click",()=>openTask());$("#taskForm").addEventListener("submit",saveTask);$("#deleteTask").addEventListener("click",deleteTask);$("#taskRecurrence").addEventListener("change",updateRecurrenceUI);$("#taskDueDate").addEventListener("change",updateRecurrenceUI);$("#customWeekdaysWrap").addEventListener("change",updateRecurrenceUI);$("#addTaskException").addEventListener("click",()=>{const d=$("#taskExceptionDate").value;if(!d)return toast("Escolha a data.");if(state.editExceptions.some(x=>x.exception_date===d))return toast("Essa data já está na lista.");state.editExceptions.push({exception_date:d,reason:$("#taskExceptionReason").value.trim()});$("#taskExceptionDate").value="";$("#taskExceptionReason").value="";renderExceptions()});$("#taskExceptionList").addEventListener("click",e=>{const b=e.target.closest("[data-remove-exception]");if(b){state.editExceptions.splice(Number(b.dataset.removeException),1);renderExceptions()}});
$$("[data-task-filter]").forEach(b=>b.addEventListener("click",()=>{state.taskFilter=b.dataset.taskFilter;$$("[data-task-filter]").forEach(x=>x.classList.toggle("active",x===b));renderTasks()}));$("#taskList").addEventListener("click",e=>{const t=e.target.closest("[data-task-toggle]");if(t)return toggleTask(t.dataset.taskToggle,"done",t.dataset.occurrenceDate);const u=e.target.closest("[data-task-unexpected]");if(u)return toggleTask(u.dataset.taskUnexpected,"unexpected",u.dataset.occurrenceDate);const ed=e.target.closest("[data-edit-task]");if(ed)return openTask(ed.dataset.editTask)});
$("#newShoppingButton").addEventListener("click",()=>openShopping());$("#shoppingForm").addEventListener("submit",saveShopping);$("#deleteShopping").addEventListener("click",deleteShopping);$$("[data-shopping-filter]").forEach(b=>b.addEventListener("click",()=>{state.shoppingFilter=b.dataset.shoppingFilter;$$("[data-shopping-filter]").forEach(x=>x.classList.toggle("active",x===b));renderShopping()}));$("#shoppingList").addEventListener("click",e=>{const t=e.target.closest("[data-shopping-toggle]");if(t)return toggleShopping(t.dataset.shoppingToggle);const ed=e.target.closest("[data-edit-shopping]");if(ed)return openShopping(ed.dataset.editShopping)});
$("#newFinanceButton").addEventListener("click",()=>openFinance());$("#financeForm").addEventListener("submit",saveFinance);$("#deleteFinance").addEventListener("click",deleteFinance);$("#financeFilter").addEventListener("change",renderFinance);$("#financeList").addEventListener("click",e=>{const p=e.target.closest("[data-finance-paid]");if(p)return toggleFinance(p.dataset.financePaid);const ed=e.target.closest("[data-edit-finance]");if(ed)return openFinance(ed.dataset.editFinance)});
$("#newBillButton").addEventListener("click",()=>openBill());$("#billForm").addEventListener("submit",saveBill);$("#deleteBill").addEventListener("click",deleteBill);$("#billList").addEventListener("click",e=>{const p=e.target.closest("[data-bill-pay]");if(p)return toggleBillPayment(p.dataset.billPay,p.dataset.billingMonth,p.dataset.dueDate);const ed=e.target.closest("[data-edit-bill]");if(ed)return openBill(ed.dataset.editBill)});
$("#petDate").value=today();$("#petDate").addEventListener("change",renderPets);$("#petGrid").addEventListener("click",e=>{const c=e.target.closest("[data-pet-care]");if(c)return togglePetCare(c.dataset.petCare,c.dataset.careType);const a=e.target.closest("[data-add-pet-care]");if(a)return addCustomPetCare(a.dataset.addPetCare)});$("#newPetHealthButton").addEventListener("click",()=>openHealth());$("#petHealthForm").addEventListener("submit",saveHealth);$("#deletePetHealth").addEventListener("click",deleteHealth);$("#petHealthList").addEventListener("click",e=>{const ed=e.target.closest("[data-edit-health]");if(ed)openHealth(ed.dataset.editHealth)});
$("#newGoalButton").addEventListener("click",()=>openGoal());$("#goalForm").addEventListener("submit",saveGoal);$("#deleteGoal").addEventListener("click",deleteGoal);$("#goalGrid").addEventListener("click",e=>{const a=e.target.closest("[data-goal-add]");if(a)return addGoalProgress(a.dataset.goalAdd);const ed=e.target.closest("[data-edit-goal]");if(ed)return openGoal(ed.dataset.editGoal)});
$("#newStockButton").addEventListener("click",()=>openStock());$("#stockForm").addEventListener("submit",saveStock);$("#deleteStock").addEventListener("click",deleteStock);$("#stockList").addEventListener("click",e=>{const s=e.target.closest("[data-stock-to-shopping]");if(s)return stockToShopping(s.dataset.stockToShopping);const ed=e.target.closest("[data-edit-stock]");if(ed)return openStock(ed.dataset.editStock)});
$("#newNoticeButton").addEventListener("click",openNotice);$("#noticeForm").addEventListener("submit",saveNotice);$("#noticeList").addEventListener("click",e=>{const r=e.target.closest("[data-read-notice]");if(r)return markNoticeRead(r.dataset.readNotice)});$("#markAllNoticesRead").addEventListener("click",markAllNoticesRead);
$("#profileForm").addEventListener("submit",saveProfile);$("#availabilityForm").addEventListener("submit",saveAvailability);$("#availabilityList").addEventListener("click",e=>{const d=e.target.closest("[data-delete-availability]");if(d)deleteAvailability(d.dataset.deleteAvailability)});$("#enableNotifications").addEventListener("click",requestNotifications);
$("#todayPlans").addEventListener("click",e=>{const b=e.target.closest("[data-today-plan]");if(b)return quickPlan(b.dataset.todayPlan)});$("#todayTasks").addEventListener("click",e=>{const b=e.target.closest("[data-today-task]");if(b)return toggleTask(b.dataset.todayTask,"done",b.dataset.occurrenceDate)});$("#todayBills").addEventListener("click",e=>{const b=e.target.closest("[data-bill-pay]");if(b)return toggleBillPayment(b.dataset.billPay,b.dataset.billingMonth,b.dataset.dueDate)});
$("#themeButton").addEventListener("click",()=>{$("#themePopover").classList.toggle("hidden");$("#menuPopover").classList.add("hidden")});$("#menuButton").addEventListener("click",()=>{$("#menuPopover").classList.toggle("hidden");$("#themePopover").classList.add("hidden")});$("#themeOptions").addEventListener("click",e=>{const b=e.target.closest("[data-theme]");if(b){applyTheme(b.dataset.theme);$("#themePopover").classList.add("hidden")}});$$("[data-close-popover]").forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.closePopover).classList.add("hidden")));$$("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>closeDialog("#"+b.dataset.closeDialog)));$("#copyInvite").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(state.board.join_code);toast("Código copiado.")}catch{toast(state.board.join_code)}});$("#notifyButton").addEventListener("click",()=>{setPage("notices");showUnreadNotices()});$("#switchBoard").addEventListener("click",()=>{if(state.mode==="demo")return toast("Modo demonstração.");renderExistingBoards();showOnly("#boardScreen")});$("#logoutButton").addEventListener("click",async()=>{if(state.mode==="demo")return toast("Modo demonstração.");await state.supabase.auth.signOut();showOnly("#authScreen")});
}
async function boot(){applyTheme(localStorage.getItem("nosso_tempo_theme")||"peach");renderThemes();defaultRange();bindEvents();if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js").catch(console.warn);if(state.mode==="demo"){demoLoad();enterApp()}else await initOnline()}
boot();
})();
